Basic Setup to load pandas and numpy libraries to perform all 4 fours joins: inner, left, right and outer

In [3]:
import pandas as pd
import numpy as np

Creating 2 tables using dataframe with 4 key elements and 4 random values in each table. Here A, B and C ate the common keys.

In [6]:
left_table =  pd.DataFrame({'key':['A','B','C','D'],'value':np.random.rand(4)})
right_table = pd.DataFrame({'key':['E','A','B','C'],'value':np.random.rand(4)})

Printing left table

In [8]:
left_table

  key     value
0   A  0.789757
1   B  0.310840
2   C  0.704958
3   D  0.377652

printing right table

In [9]:
right_table

  key     value
0   E  0.446299
1   A  0.894405
2   B  0.111282
3   C  0.941089

INNER Join

In [10]:
left_table.merge(right_table,on='key', how='inner')

  key   value_x   value_y
0   A  0.789757  0.894405
1   B  0.310840  0.111282
2   C  0.704958  0.941089

LEFT join

In [11]:
left_table.merge(right_table,on='key', how='left')

  key   value_x   value_y
0   A  0.789757  0.894405
1   B  0.310840  0.111282
2   C  0.704958  0.941089
3   D  0.377652       NaN

RIGHT join

In [12]:
left_table.merge(right_table,on='key', how='right')

  key   value_x   value_y
0   E       NaN  0.446299
1   A  0.789757  0.894405
2   B  0.310840  0.111282
3   C  0.704958  0.941089

OUTER join

In [13]:
left_table.merge(right_table,on='key', how='outer')

  key   value_x   value_y
0   A  0.789757  0.894405
1   B  0.310840  0.111282
2   C  0.704958  0.941089
3   D  0.377652       NaN
4   E       NaN  0.446299